spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  data:
    rest:
      base-path: /api/v1
  sql:
    init:
      mode: always
      data-locations: classpath:sql-scripts/create-roles.sql

keystore:
  passphrase: ${KEYSTORE_PASSPHRASE}